version: "3.8"

services:
  shadowkickers:
    # The image tag will be replaced by GitHub Actions workflow in the deploy branch
    image: ghcr.io/korjavin/shadowkickers:d352e01dce85b8d5710fca6a25b0ce88f0a45162
    container_name: shadowkickers
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shadowkickers.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.shadowkickers.entrypoints=websecure"
      - "traefik.http.routers.shadowkickers.tls.certresolver=myresolver"
      - "traefik.http.services.shadowkickers.loadbalancer.server.port=8080"
    restart: unless-stopped

networks:
  traefik_network:
    name: ${NETWORK_NAME:-traefik_network}
    external: true
